name: Deploy ECS Config Server
on:
  push:
    branches:
      - test-updates

env:
  AWS_REGION: '${{ secrets.AWS_REGION }}'
  ENVIRONMENT: STAGE
  AWS_STAGE: '${{ secrets.AWS_ARN }}'
  REGISTRY: 'ghcr.io'
  TAG: 'latest'

jobs:
  push:
    name: push
    runs-on: ubuntu-latest

    permissions:
      contents: read
      id-token: write

    steps:
      - name: checkout the source code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: login to ghcr
        id: ghcr
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GHCR_TOKEN }}

      - name: build / tag / push docker image into ghcr
        id: build-and-push
        uses: docker/build-push-action@v3
        with:
          context: .
          file: server.dockerfile
          push: true
          tags: ${{ env.REGISTRY }}/${{ github.repository }}/config-server-stage:${{ env.TAG }}   

  deploy:
    needs: push
    name: deploy
    runs-on: ubuntu-latest

    permissions:
      contents: read
      id-token: write

    steps:
      - name: checkout the source code
        uses: actions/checkout@v3
        
      - name: checkout ecs repo
        uses: actions/checkout@v3
        with:
          repository: sygmaprotocol/devops
          token: ${{ secrets.GHCR_TOKEN }}

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: arn:aws:iam::${{ env.AWS_STAGE }}:role/github-actions-${{ env.ENVIRONMENT }}-chainbridge
          aws-region: ${{ env.AWS_REGION }}
          role-session-name: GithubActions

      - name: Deploy to Amazon ECS
        uses: aws-actions/amazon-ecs-deploy-task-definition@v1
        with:
          task-definition: 'sygma-ui/ecs/task_definition-config-server-${{ env.ENVIRONMENT }}.json'
          service: 'config-server-service-${{ env.ENVIRONMENT }}'
          cluster: 'config-server-${{ env.ENVIRONMENT }}'
          wait-for-service-stability: true
